### ISSUE TITLE
Angular and material 11 support.

### ISSUE THREAD

**Issue by intermx-vignesh** [HaidarZ/ng-mat-select-infinite-scroll#18]
I don't see a big issues in updating the dependency list to support the latest angular versions.

Is there a breaking change that prevents this project from being updated? would try to help if that's the case.

I inherited a codebase from someone else which made heavy usage of this plugin and now I'm trying to update to Angular 11.

**Comment by HaidarZ** [comment]
Hello,
I'll work on updating the library to latest angular as soon as possible.
Just need some time to check if there's any breaking change.

**Comment by Khazii** [comment]
Hi,

Since this issue was opened Angular is now v12, I had no issues with this package on v11 but it seems Material has removed/changed some exports that this package was dependent on.

`
./node_modules/ng-mat-select-infinite-scroll/__ivy_ngcc__/fesm2015/ng-mat-select-infinite-scroll.js:17:34-55 - Error: export 'SELECT_ITEM_HEIGHT_EM' (imported as 'SELECT_ITEM_HEIGHT_EM') was not found in '@angular/material/select' (possible exports: MAT_SELECT_CONFIG, MAT_SELECT_SCROLL_STRATEGY, MAT_SELECT_SCROLL_STRATEGY_PROVIDER, MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY, MAT_SELECT_TRIGGER, MatSelect, MatSelectChange, MatSelectModule, MatSelectTrigger, _MatSelectBase, matSelectAnimations)

./node_modules/ng-mat-select-infinite-scroll/__ivy_ngcc__/fesm2015/ng-mat-select-infinite-scroll.js:66:67-88 - Error: export 'SELECT_ITEM_HEIGHT_EM' (imported as 'SELECT_ITEM_HEIGHT_EM') was not found in '@angular/material/select' (possible exports: MAT_SELECT_CONFIG, MAT_SELECT_SCROLL_STRATEGY, MAT_SELECT_SCROLL_STRATEGY_PROVIDER, MAT_SELECT_SCROLL_STRATEGY_PROVIDER_FACTORY, MAT_SELECT_TRIGGER, MatSelect, MatSelectChange, MatSelectModule, MatSelectTrigger, _MatSelectBase, matSelectAnimations)
`

Hope this helps

**Comment by angelaki** [comment]
Any estimations when this library gets updated? Would love to upgrade to ng12

**Comment by angelaki** [comment]
Any news on this? @Khazii have you found a solution, yet? Or still waiting for this to get updated, too?

**Comment by parse** [comment]
@angelaki I just submitted a PR that contains a fix.

**Comment by HaidarZ** [comment]
I'm working on the workaround, will be out soon.
This issue is related to the angular/material bug https://github.com/angular/components/issues/22787
